default_language_version:
    python: python3.11

exclude: ^(kubernetes)/

repos:
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length, "99"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: debug-statements
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [-m, "3", --profile, "black"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--skip, "B101,B104,B301,B311,B403,B404,B603,B607", --exclude, "tests"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--extend-ignore, "E203,W503", --max-line-length, "99"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --ignore-missing-imports, --allow-any-generics]
        additional_dependencies: [pydantic]
