"""rota que os arautos foram lanćados

Revision ID: 0e4528fc45c9
Revises: 2cfceb9fa7e9
Create Date: 2022-10-27 13:49:33.314608

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e4528fc45c9"
down_revision = "2cfceb9fa7e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matchup_map", sa.Column("first_herald_route", sa.String(), nullable=True))
    op.add_column("matchup_map", sa.Column("second_herald_route", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchup_map", "second_herald_route")
    op.drop_column("matchup_map", "first_herald_route")
    # ### end Alembic commands ###
