"""second third drake

Revision ID: 26b637ffe3ff
Revises: f5c9b9cdb7cd
Create Date: 2022-07-15 09:52:12.763089

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26b637ffe3ff"
down_revision = "f5c9b9cdb7cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matchup_map", sa.Column("team_second_drake", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("second_drake_teamfight", sa.Boolean(), nullable=True))
    op.add_column("matchup_map", sa.Column("second_drake_type", sa.String(), nullable=True))
    op.add_column("matchup_map", sa.Column("team_third_drake", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("third_drake_teamfight", sa.Boolean(), nullable=True))
    op.add_column("matchup_map", sa.Column("third_drake_type", sa.String(), nullable=True))
    op.create_foreign_key(None, "matchup_map", "team", ["team_second_drake"], ["id"])
    op.create_foreign_key(None, "matchup_map", "team", ["team_third_drake"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_column("matchup_map", "third_drake_type")
    op.drop_column("matchup_map", "third_drake_teamfight")
    op.drop_column("matchup_map", "team_third_drake")
    op.drop_column("matchup_map", "second_drake_type")
    op.drop_column("matchup_map", "second_drake_teamfight")
    op.drop_column("matchup_map", "team_second_drake")
    # ### end Alembic commands ###
