"""campo de vod do jogo

Revision ID: 2a66f52f49d4
Revises: 0e4528fc45c9
Create Date: 2022-11-12 13:52:26.217534

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a66f52f49d4"
down_revision = "0e4528fc45c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matchup", sa.Column("vod_link", sa.String(), nullable=True))
    op.add_column("matchup_map", sa.Column("vod_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchup_map", "vod_link")
    op.drop_column("matchup", "vod_link")
    op.drop_table("single_view")
    op.drop_table("picks_bans_prio_view")
    op.drop_table("objective_view")
    # ### end Alembic commands ###
