"""dados de objetivos e torres

Revision ID: 2cfceb9fa7e9
Revises: 7d01e71e751d
Create Date: 2022-10-27 13:41:33.198959

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2cfceb9fa7e9"
down_revision = "7d01e71e751d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matchup_map", sa.Column("blue_turrets_destroyed", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("red_turrets_destroyed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchup_map", "red_turrets_destroyed")
    op.drop_column("matchup_map", "blue_turrets_destroyed")
    op.drop_table("single_view")
    op.drop_table("picks_bans_prio_view")
    # ### end Alembic commands ###
