"""campo patch

Revision ID: 46b0020fb15f
Revises: 09952a8b362b
Create Date: 2022-05-23 18:44:00.606404

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46b0020fb15f"
down_revision = "09952a8b362b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("auth_role_id_key", "auth_role", ["id"])
    op.create_unique_constraint("auth_role_user_id_key", "auth_role_user", ["id"])
    op.create_unique_constraint("auth_user_id_key", "auth_user", ["id"])
    op.create_unique_constraint("champion_id_key", "champion", ["id"])
    op.create_unique_constraint("matchup_id_key", "matchup", ["id"])
    op.add_column("matchup_map", sa.Column("patch", sa.String(), nullable=True))
    op.create_unique_constraint("player_id_key", "player", ["id"])
    op.create_unique_constraint("team_id_key", "team", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("team_id_key", "team", type_="unique")
    op.drop_constraint("player_id_key", "player", type_="unique")
    op.drop_column("matchup_map", "patch")
    op.drop_constraint("matchup_id_key", "matchup", type_="unique")
    op.drop_constraint("champion_id_key", "champion", type_="unique")
    op.drop_constraint("auth_user_id_key", "auth_user", type_="unique")
    op.drop_constraint("auth_role_user_id_key", "auth_role_user", type_="unique")
    op.drop_constraint("auth_role_id_key", "auth_role", type_="unique")
    # ### end Alembic commands ###
