"""campo patch

Revision ID: 46b0020fb15f
Revises: 09952a8b362b
Create Date: 2022-05-23 18:44:00.606404

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46b0020fb15f"
down_revision = "09952a8b362b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "auth_role", ["id"])
    op.create_unique_constraint(None, "auth_role_user", ["id"])
    op.create_unique_constraint(None, "auth_user", ["id"])
    op.create_unique_constraint(None, "champion", ["id"])
    op.create_unique_constraint(None, "matchup", ["id"])
    op.add_column("matchup_map", sa.Column("patch", sa.String(), nullable=True))
    op.create_unique_constraint(None, "player", ["id"])
    op.create_unique_constraint(None, "team", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team", type_="unique")
    op.drop_constraint(None, "player", type_="unique")
    op.drop_column("matchup_map", "patch")
    op.drop_constraint(None, "matchup", type_="unique")
    op.drop_constraint(None, "champion", type_="unique")
    op.drop_constraint(None, "auth_user", type_="unique")
    op.drop_constraint(None, "auth_role_user", type_="unique")
    op.drop_constraint(None, "auth_role", type_="unique")
    op.drop_table("single_view")
    # ### end Alembic commands ###
