"""campos de analise para novos KPIs

Revision ID: 4d4c6414eb63
Revises: 1f2d650ec484
Create Date: 2022-06-13 20:55:27.655850

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d4c6414eb63"
down_revision = "1f2d650ec484"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matchup_map", sa.Column("team_first_blood", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("player_first_blood", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("player_first_death", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("place_first_blood", sa.String(), nullable=True))
    op.add_column("matchup_map", sa.Column("team_first_herald", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("first_herald_teamfight", sa.Boolean(), nullable=True))
    op.add_column("matchup_map", sa.Column("team_first_drake", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("first_drake_teamfight", sa.Boolean(), nullable=True))
    op.add_column(
        "matchup_map",
        sa.Column(
            "first_drake_type",
            sa.Enum("cloud", "mountain", "infernal", "ocean", name="drake"),
            nullable=True,
        ),
    )
    op.add_column("matchup_map", sa.Column("team_first_tower", sa.Integer(), nullable=True))
    op.add_column(
        "matchup_map",
        sa.Column(
            "first_tower_route",
            sa.Enum("baron", "jungle", "mid", "dragon", "sup", name="role"),
            nullable=True,
        ),
    )
    op.add_column("matchup_map", sa.Column("first_tower_herald", sa.Boolean(), nullable=True))
    op.create_foreign_key(None, "matchup_map", "team", ["team_first_blood"], ["id"])
    op.create_foreign_key(None, "matchup_map", "team", ["team_first_tower"], ["id"])
    op.create_foreign_key(None, "matchup_map", "team", ["team_first_herald"], ["id"])
    op.create_foreign_key(None, "matchup_map", "team", ["team_first_drake"], ["id"])
    op.create_foreign_key(None, "matchup_map", "player", ["player_first_blood"], ["id"])
    op.create_foreign_key(None, "matchup_map", "player", ["player_first_death"], ["id"])
    op.create_unique_constraint(None, "tournament_lineup", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tournament_lineup", type_="unique")
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_column("matchup_map", "first_tower_herald")
    op.drop_column("matchup_map", "first_tower_route")
    op.drop_column("matchup_map", "team_first_tower")
    op.drop_column("matchup_map", "first_drake_type")
    op.drop_column("matchup_map", "first_drake_teamfight")
    op.drop_column("matchup_map", "team_first_drake")
    op.drop_column("matchup_map", "first_herald_teamfight")
    op.drop_column("matchup_map", "team_first_herald")
    op.drop_column("matchup_map", "place_first_blood")
    op.drop_column("matchup_map", "player_first_death")
    op.drop_column("matchup_map", "player_first_blood")
    op.drop_column("matchup_map", "team_first_blood")
    # ### end Alembic commands ###
