"""second herald and stealed indicator

Revision ID: 7d01e71e751d
Revises: 26b637ffe3ff
Create Date: 2022-10-26 13:14:44.653524

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7d01e71e751d"
down_revision = "26b637ffe3ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("matchup_map", sa.Column("first_herald_stealed", sa.Boolean(), nullable=True))
    op.add_column("matchup_map", sa.Column("team_second_herald", sa.Integer(), nullable=True))
    op.add_column("matchup_map", sa.Column("second_herald_teamfight", sa.Boolean(), nullable=True))
    op.add_column("matchup_map", sa.Column("second_herald_stealed", sa.Boolean(), nullable=True))
    op.add_column("matchup_map", sa.Column("first_drake_stealed", sa.Boolean(), nullable=True))
    op.add_column("matchup_map", sa.Column("second_drake_stealed", sa.Boolean(), nullable=True))
    op.add_column("matchup_map", sa.Column("third_drake_stealed", sa.Boolean(), nullable=True))
    op.create_foreign_key(None, "matchup_map", "team", ["team_second_herald"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "matchup_map", type_="foreignkey")
    op.drop_column("matchup_map", "third_drake_stealed")
    op.drop_column("matchup_map", "second_drake_stealed")
    op.drop_column("matchup_map", "first_drake_stealed")
    op.drop_column("matchup_map", "second_herald_stealed")
    op.drop_column("matchup_map", "second_herald_teamfight")
    op.drop_column("matchup_map", "team_second_herald")
    op.drop_column("matchup_map", "first_herald_stealed")
    # ### end Alembic commands ###
