"""mais campos do champion

Revision ID: a603f4a3bb0a
Revises: 807aa834b4bd
Create Date: 2023-04-20 16:56:04.384217

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a603f4a3bb0a"
down_revision = "807aa834b4bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("champion", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("riot_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("champion", schema=None) as batch_op:
        batch_op.drop_column("riot_id")
        batch_op.drop_column("avatar")

    # ### end Alembic commands ###
