"""inicio da logica de torneio

Revision ID: c67467713733
Revises: 46b0020fb15f
Create Date: 2022-05-23 19:23:31.777257

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c67467713733"
down_revision = "46b0020fb15f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournament",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", postgresql.UUID(), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("tag", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("split", sa.Integer(), nullable=True),
        sa.Column("phases", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "tournament_team",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", postgresql.UUID(), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("entry_phase", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ("team_id",),
            ["tournament.id"],
        ),
        sa.ForeignKeyConstraint(
            ("tournament_id",),
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.add_column("matchup", sa.Column("tournament_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "matchup_tournament_id_fkey", "matchup", "tournament", ["tournament_id"], ["id"]
    )
    op.add_column("matchup_map", sa.Column("tournament_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "matchup_map_tournament_id_fkey", "matchup_map", "tournament", ["tournament_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("matchup_map_tournament_id_fkey", "matchup_map", type_="foreignkey")
    op.drop_column("matchup_map", "tournament_id")
    op.drop_constraint("matchup_tournament_id_fkey", "matchup", type_="foreignkey")
    op.drop_column("matchup", "tournament_id")
    op.drop_table("tournament_team")
    op.drop_table("tournament")
    # ### end Alembic commands ###
