"""corrigir tabela time e torneio

Revision ID: db7d1421fc7d
Revises: c67467713733
Create Date: 2022-05-23 19:48:32.948163

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db7d1421fc7d"
down_revision = "c67467713733"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tournament", sa.Column("female_only", sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, "tournament", ["id"])
    op.create_unique_constraint(None, "tournament_teams", ["id"])
    op.drop_constraint("tournament_teams_team_id_fkey", "tournament_team", type_="foreignkey")
    op.create_foreign_key(None, "tournament_team", "team", ["team_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tournament_team", type_="foreignkey")
    op.create_foreign_key(
        "tournament_teams_team_id_fkey", "tournament_team", "tournament", ["team_id"], ["id"]
    )
    op.drop_constraint(None, "tournament_team", type_="unique")
    op.drop_constraint(None, "tournament", type_="unique")
    op.drop_column("tournament", "female_only")
    op.drop_table("single_view")
    # ### end Alembic commands ###
