"""Campo tipo drake refeito

Revision ID: f5c9b9cdb7cd
Revises: d9aab1aef720
Create Date: 2022-06-13 21:12:06.457720

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5c9b9cdb7cd"
down_revision = "d9aab1aef720"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matchup_map", sa.Column("first_drake_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchup_map", "first_drake_type")
    op.drop_table("single_view")
    op.drop_table("picks_bans_prio_view")
    # ### end Alembic commands ###
