from sqlalchemy import Boolean, Column, Integer, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy_serializer import SerializerMixin

from db_config import db


class ObjectiveFields:
    first_blood = Column(Boolean)
    place_first_blood = Column(String)
    first_herald = Column(String)
    first_herald_teamfight = Column(Boolean)
    first_herald_stealed = Column(Boolean)
    first_herald_route = Column(String)
    second_herald = Column(String)
    second_herald_teamfight = Column(Boolean)
    second_herald_stealed = Column(Boolean)
    second_herald_route = Column(String)
    first_tower = Column(String)
    first_tower_route = Column(String)
    first_tower_herald = Column(Boolean)
    first_drake = Column(String)
    first_drake_teamfight = Column(Boolean)
    first_drake_stealed = Column(Boolean)
    first_drake_type = Column(String)
    second_drake = Column(String)
    second_drake_teamfight = Column(Boolean)
    second_drake_stealed = Column(Boolean)
    second_drake_type = Column(String)
    third_drake = Column(String)
    third_drake_teamfight = Column(Boolean)
    third_drake_stealed = Column(Boolean)
    third_drake_type = Column(String)
    turrets_destroyed = Column(Boolean)


class SingleView(db.Model, ObjectiveFields, SerializerMixin):
    __tablename__ = "single_view"

    id = Column(UUID, primary_key=True)
    map_id = Column(Integer)
    matchup_id = Column(Integer)
    tournament_id = Column(Integer)
    map_number = Column(Integer)
    patch = Column(String)
    team_id = Column(Integer)
    side = Column(String)
    length = Column(String)
    length_sec = Column(String)
    winner = Column(Integer)
    winner_side = Column(String)
    ban_1 = Column(Integer)
    ban_2 = Column(Integer)
    ban_3 = Column(Integer)
    ban_4 = Column(Integer)
    ban_5 = Column(Integer)
    pick_1 = Column(Integer)
    pick_2 = Column(Integer)
    pick_3 = Column(Integer)
    pick_4 = Column(Integer)
    pick_5 = Column(Integer)
    baron_pick = Column(Integer)
    jungle_pick = Column(Integer)
    mid_pick = Column(Integer)
    dragon_pick = Column(Integer)
    sup_pick = Column(Integer)
    baron_kills = Column(Integer)
    jungle_kills = Column(Integer)
    mid_kills = Column(Integer)
    dragon_kills = Column(Integer)
    sup_kills = Column(Integer)
    baron_deaths = Column(Integer)
    jungle_deaths = Column(Integer)
    mid_deaths = Column(Integer)
    dragon_deaths = Column(Integer)
    sup_deaths = Column(Integer)
    baron_assists = Column(Integer)
    jungle_assists = Column(Integer)
    mid_assists = Column(Integer)
    dragon_assists = Column(Integer)
    sup_assists = Column(Integer)
    baron_dmg_taken = Column(Integer)
    jungle_dmg_taken = Column(Integer)
    mid_dmg_taken = Column(Integer)
    dragon_dmg_taken = Column(Integer)
    sup_dmg_taken = Column(Integer)
    baron_dmg_dealt = Column(Integer)
    jungle_dmg_dealt = Column(Integer)
    mid_dmg_dealt = Column(Integer)
    dragon_dmg_dealt = Column(Integer)
    sup_dmg_dealt = Column(Integer)
    baron_total_gold = Column(Integer)
    jungle_total_gold = Column(Integer)
    mid_total_gold = Column(Integer)
    dragon_total_gold = Column(Integer)
    sup_total_gold = Column(Integer)
    baron_player = Column(Integer)
    jungle_player = Column(Integer)
    mid_player = Column(Integer)
    dragon_player = Column(Integer)
    sup_player = Column(Integer)
    player_first_blood = Column(Integer)
    player_first_death = Column(Integer)
    turrets_destroyed = Column(Integer)


class PicksBansPrioView(db.Model, ObjectiveFields, SerializerMixin):
    __tablename__ = "picks_bans_prio_view"

    uuid = Column(UUID, primary_key=True)
    matchup_id = Column(Integer)
    map_id = Column(Integer)
    map_number = Column(Integer)
    patch = Column(String)
    side = Column(String)
    length = Column(String)
    length_sec = Column(Integer)
    tournament_id = Column(Integer)
    team_id = Column(Integer)
    winner = Column(Boolean)
    ban_id = Column(Integer)
    pick_id = Column(String)
    position = Column(Integer)
    pick_rotation = Column(Integer)
    ban_rotation = Column(Integer)
    role = Column(String)
    is_blind = Column(Boolean)
    player = Column(Integer)
    kills = Column(Integer)
    deaths = Column(Integer)
    assists = Column(Integer)
    dmg_taken = Column(Integer)
    dmg_dealt = Column(Integer)
    total_gold = Column(Integer)
    is_player_first_blood = Column(Boolean)
    is_player_first_death = Column(Boolean)


class ObjectiveView(db.Model, SerializerMixin):
    __tablename__ = "objective_view"

    uuid = Column(UUID, primary_key=True)
    matchup_id = Column(Integer)
    map_id = Column(Integer)
    map_number = Column(Integer)
    patch = Column(String)
    side = Column(String)
    tournament_id = Column(Integer)
    winner = Column(Boolean)
    length = Column(String)
    length_sec = Column(Integer)
    team_id = Column(Integer)
    team_giver_id = Column(Integer)
    objective_type = Column(String)
    objective_name = Column(String)
    objective_order = Column(Integer)
    with_teamfight = Column(Boolean)
    is_stealed = Column(Boolean)
    place = Column(String)
    with_herald = Column(Boolean)
    killer = Column(Integer)
    role_killer = Column(String)
    champion_killer = Column(Integer)
    victim = Column(Integer)
    role_victim = Column(String)
    champion_victim = Column(Integer)
